# Generated by Django 6.0.4 on 2026-04-28 00:55

import raterapi.models.gamepicture
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0002_alter_gamerating_game'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamepicture',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gamepicture',
            name='action_pic',
            field=models.ImageField(null=True, upload_to=raterapi.models.gamepicture.game_image_upload_path),
        ),
        migrations.RemoveField(
            model_name='gamepicture',
            name='url',
        ),
    ]
