# Generated by Django 6.0.4 on 2026-04-28 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0003_alter_gamepicture_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamepicture',
            old_name='user',
            new_name='player',
        ),
    ]
