# Generated by Django 6.0.4 on 2026-04-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0004_rename_user_gamepicture_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bgg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
